### ISSUE TITLE
server ping not replied

### ISSUE THREAD

**Issue by dreamer2** [mattn/go-xmpp#83]
receiving ping from openfire 4.0.1 with double quote mark but current code check only single quotes

```
		case *clientIQ:
			if bytes.Equal(v.Query, []byte(`<ping xmlns='urn:xmpp:ping'/>`)) || bytes.Equal(v.Query, []byte(`<ping xmlns="urn:xmpp:ping"/>`)) {

```

**Comment by mattn** [comment]
it's not issue of go-xmpp.

**Comment by dreamer2** [comment]
if both quotes type legal in xml formatting, may be better add check for double quotes?

anyway thank you for project

**Comment by mattn** [comment]
Ah, sorry. I was confused. This is checking part in go-xmpp. I'll look into it.
