### ISSUE TITLE
Change "notls" to the true

### ISSUE THREAD

**Issue by neil605164** [mattn/go-xmpp#91]
Hi，When i edit "example.go" notls key to the 「true」 ，then i run the example.go is return 「starttls handshake: x509: certificate signed by unknown authority」，Can you help me to solve it

**Comment by mattn** [comment]
Whether the NonTLS is supported is depend on the server.

**Comment by neil605164** [comment]
I use ejabberd in xmpp，this is my ejabberd.yml setting

**Comment by mattn** [comment]
Closed by https://github.com/mattn/go-xmpp/pull/110
